[project]
name = "alpha-1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.14.0",
    "numpy>=2.3.1",
    "python-chess>=1.999",
    "torch>=2.7.1",
]
